### ISSUE TITLE
List View: Maximum view state size limit 

### ISSUE THREAD

**Issue by aranwe** [SFDO-Community/declarative-lookup-rollup-summaries#1253]
**Describe the bug**
When accessing "Lookup Rollup List View" in an org with 49 DLRSes + 40k deleted CronTriggers I get:
Maximum view state size limit (170KB) exceeded. Actual view state size for this page was 286.157KB

**To Reproduce**

1. Create >=49DLRSes + 40k deleted CronTriggers
2. Go to Lookup Rollup List View
3. See error

**Expected behavior**
See the list of DLRSes

**Screenshots**
![image](https://user-images.githubusercontent.com/592098/193804577-2450b793-7355-43eb-a57e-30f22511dbc7.png)

//EDITED to include the CronTrigger count

**Comment by aranwe** [comment]
Most likely caused by ```new CronTriggersSelector().selectAllScheduledApex()```
Adding  ```State NOT IN ('DELETED')``` to the Selector should fix the issue as we should not need Deleted CronTriggers anywhere anyway.

**Comment by aranwe** [comment]
Btw: as far as I know FFLib queryFactory overwrites setCondition:
So in the following (from CronTriggerSelector)
```java
//CronTriggerSelector: line 37
      newQueryFactory()
        .selectfield('CronJobDetail.Name')
        .setCondition('CronJobDetail.JobType = \'7\'')
        .setCondition('CronJobDetail.Name LIKE :id')
        .setLimit(1)
        .tosoql()
```

the first setCondition is always overwritten by the 2nd.

**Comment by Szandor72** [comment]
Thanks @aranwe 

Are these now two issues? One around `.setCondition` and one around the amount of deleted contriggers/viewstate. 

It seems you have analyzed this thoroughly, would you be willing to fix it as well? Just merged your first PR, happy to receive a second. 

In theory, viewState could explode even with a fix. Do you deem this likely?

**Comment by aranwe** [comment]
@Szandor72 
Yup -> these are 2 separate issues, the other one being minor.

Yes, I should be able to look into this and make a PR -> though most likely next week :) 

@viewStateSize -> well it possibly could, but I think its highly unlikely as there is 100 Cron job limit. It would most likely break if/once SF adds some additional state to the CronTrigger as all the current ones (except `DELETED`) are AFAIK counting towards the limit.

The other potential cause of View State Size exploding would be having thousands `LookupRollupSummary2__mdt` but again -> pretty unlikely. (how many DLRSes is the most you have seen in an org anyway?)

**Comment by aheber** [comment]
This should be improved in the new LWC wizard available in v2.21. It doesn't fix the list view UI but supersedes it. Much of the VF UI will be deprecated and removed as that new wizard starts to take place as the primary UI.
